# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://projectiris.io/
title: IRIS
email: feedback@petitio.ch
author: Your Name
description: > # "Write an awesome description for your new site here.
  A petiton platform for enabling local change
copyright: 'Copyright &copy; 2017 AZ Medien AG. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: GitHub
    logoKey: github
    url: https://github.com/iris-dni
